### ISSUE TITLE
Symfony 3.3

### ISSUE THREAD

**Issue by florianderycke** [IQ2i/PrestaShop-WebService-Bundle#3]
Hello,

Tested on Symfony 3.3.8.
For info, it works perfectly after replacing:
` arguments: [@service_container]`
by 
`arguments: ['@service_container']`
in the iq2i\prestashop-webservice-bundle\IQ2i\PrestaShopWebServiceBundle\Resources\config.yml

**Comment by loicsapone** [comment]
Hi,

I pushed the version 1.2.0 in which you will find a fix with the quotes.

**Comment by florianderycke** [comment]
Great, thanks!
